export interface DepartmentData {
  code: string;   // "13", "75", "2A", etc.
  slug: string;   // "bouches-du-rhone", "paris", etc.
  name: string;   // "Bouches-du-Rhône"
  region: string;
}

export const DEPARTMENTS: DepartmentData[] = [
  { code: '01', slug: 'ain',                        name: "Ain",                         region: "Auvergne-Rhône-Alpes" },
  { code: '02', slug: 'aisne',                      name: "Aisne",                       region: "Hauts-de-France" },
  { code: '03', slug: 'allier',                     name: "Allier",                      region: "Auvergne-Rhône-Alpes" },
  { code: '04', slug: 'alpes-de-haute-provence',    name: "Alpes-de-Haute-Provence",     region: "Provence-Alpes-Côte d'Azur" },
  { code: '05', slug: 'hautes-alpes',               name: "Hautes-Alpes",                region: "Provence-Alpes-Côte d'Azur" },
  { code: '06', slug: 'alpes-maritimes',            name: "Alpes-Maritimes",             region: "Provence-Alpes-Côte d'Azur" },
  { code: '07', slug: 'ardeche',                    name: "Ardèche",                     region: "Auvergne-Rhône-Alpes" },
  { code: '08', slug: 'ardennes',                   name: "Ardennes",                    region: "Grand Est" },
  { code: '09', slug: 'ariege',                     name: "Ariège",                      region: "Occitanie" },
  { code: '10', slug: 'aube',                       name: "Aube",                        region: "Grand Est" },
  { code: '11', slug: 'aude',                       name: "Aude",                        region: "Occitanie" },
  { code: '12', slug: 'aveyron',                    name: "Aveyron",                     region: "Occitanie" },
  { code: '13', slug: 'bouches-du-rhone',           name: "Bouches-du-Rhône",            region: "Provence-Alpes-Côte d'Azur" },
  { code: '14', slug: 'calvados',                   name: "Calvados",                    region: "Normandie" },
  { code: '15', slug: 'cantal',                     name: "Cantal",                      region: "Auvergne-Rhône-Alpes" },
  { code: '16', slug: 'charente',                   name: "Charente",                    region: "Nouvelle-Aquitaine" },
  { code: '17', slug: 'charente-maritime',          name: "Charente-Maritime",           region: "Nouvelle-Aquitaine" },
  { code: '18', slug: 'cher',                       name: "Cher",                        region: "Centre-Val de Loire" },
  { code: '19', slug: 'correze',                    name: "Corrèze",                     region: "Nouvelle-Aquitaine" },
  { code: '2A', slug: 'corse-du-sud',               name: "Corse-du-Sud",                region: "Corse" },
  { code: '2B', slug: 'haute-corse',                name: "Haute-Corse",                 region: "Corse" },
  { code: '21', slug: 'cote-d-or',                  name: "Côte-d'Or",                   region: "Bourgogne-Franche-Comté" },
  { code: '22', slug: 'cotes-d-armor',              name: "Côtes-d'Armor",               region: "Bretagne" },
  { code: '23', slug: 'creuse',                     name: "Creuse",                      region: "Nouvelle-Aquitaine" },
  { code: '24', slug: 'dordogne',                   name: "Dordogne",                    region: "Nouvelle-Aquitaine" },
  { code: '25', slug: 'doubs',                      name: "Doubs",                       region: "Bourgogne-Franche-Comté" },
  { code: '26', slug: 'drome',                      name: "Drôme",                       region: "Auvergne-Rhône-Alpes" },
  { code: '27', slug: 'eure',                       name: "Eure",                        region: "Normandie" },
  { code: '28', slug: 'eure-et-loir',               name: "Eure-et-Loir",                region: "Centre-Val de Loire" },
  { code: '29', slug: 'finistere',                  name: "Finistère",                   region: "Bretagne" },
  { code: '30', slug: 'gard',                       name: "Gard",                        region: "Occitanie" },
  { code: '31', slug: 'haute-garonne',              name: "Haute-Garonne",               region: "Occitanie" },
  { code: '32', slug: 'gers',                       name: "Gers",                        region: "Occitanie" },
  { code: '33', slug: 'gironde',                    name: "Gironde",                     region: "Nouvelle-Aquitaine" },
  { code: '34', slug: 'herault',                    name: "Hérault",                     region: "Occitanie" },
  { code: '35', slug: 'ille-et-vilaine',            name: "Ille-et-Vilaine",             region: "Bretagne" },
  { code: '36', slug: 'indre',                      name: "Indre",                       region: "Centre-Val de Loire" },
  { code: '37', slug: 'indre-et-loire',             name: "Indre-et-Loire",              region: "Centre-Val de Loire" },
  { code: '38', slug: 'isere',                      name: "Isère",                       region: "Auvergne-Rhône-Alpes" },
  { code: '39', slug: 'jura',                       name: "Jura",                        region: "Bourgogne-Franche-Comté" },
  { code: '40', slug: 'landes',                     name: "Landes",                      region: "Nouvelle-Aquitaine" },
  { code: '41', slug: 'loir-et-cher',               name: "Loir-et-Cher",                region: "Centre-Val de Loire" },
  { code: '42', slug: 'loire',                      name: "Loire",                       region: "Auvergne-Rhône-Alpes" },
  { code: '43', slug: 'haute-loire',                name: "Haute-Loire",                 region: "Auvergne-Rhône-Alpes" },
  { code: '44', slug: 'loire-atlantique',           name: "Loire-Atlantique",            region: "Pays de la Loire" },
  { code: '45', slug: 'loiret',                     name: "Loiret",                      region: "Centre-Val de Loire" },
  { code: '46', slug: 'lot',                        name: "Lot",                         region: "Occitanie" },
  { code: '47', slug: 'lot-et-garonne',             name: "Lot-et-Garonne",              region: "Nouvelle-Aquitaine" },
  { code: '48', slug: 'lozere',                     name: "Lozère",                      region: "Occitanie" },
  { code: '49', slug: 'maine-et-loire',             name: "Maine-et-Loire",              region: "Pays de la Loire" },
  { code: '50', slug: 'manche',                     name: "Manche",                      region: "Normandie" },
  { code: '51', slug: 'marne',                      name: "Marne",                       region: "Grand Est" },
  { code: '52', slug: 'haute-marne',                name: "Haute-Marne",                 region: "Grand Est" },
  { code: '53', slug: 'mayenne',                    name: "Mayenne",                     region: "Pays de la Loire" },
  { code: '54', slug: 'meurthe-et-moselle',         name: "Meurthe-et-Moselle",          region: "Grand Est" },
  { code: '55', slug: 'meuse',                      name: "Meuse",                       region: "Grand Est" },
  { code: '56', slug: 'morbihan',                   name: "Morbihan",                    region: "Bretagne" },
  { code: '57', slug: 'moselle',                    name: "Moselle",                     region: "Grand Est" },
  { code: '58', slug: 'nievre',                     name: "Nièvre",                      region: "Bourgogne-Franche-Comté" },
  { code: '59', slug: 'nord',                       name: "Nord",                        region: "Hauts-de-France" },
  { code: '60', slug: 'oise',                       name: "Oise",                        region: "Hauts-de-France" },
  { code: '61', slug: 'orne',                       name: "Orne",                        region: "Normandie" },
  { code: '62', slug: 'pas-de-calais',              name: "Pas-de-Calais",               region: "Hauts-de-France" },
  { code: '63', slug: 'puy-de-dome',                name: "Puy-de-Dôme",                 region: "Auvergne-Rhône-Alpes" },
  { code: '64', slug: 'pyrenees-atlantiques',       name: "Pyrénées-Atlantiques",        region: "Nouvelle-Aquitaine" },
  { code: '65', slug: 'hautes-pyrenees',            name: "Hautes-Pyrénées",             region: "Occitanie" },
  { code: '66', slug: 'pyrenees-orientales',        name: "Pyrénées-Orientales",         region: "Occitanie" },
  { code: '67', slug: 'bas-rhin',                   name: "Bas-Rhin",                    region: "Grand Est" },
  { code: '68', slug: 'haut-rhin',                  name: "Haut-Rhin",                   region: "Grand Est" },
  { code: '69', slug: 'rhone',                      name: "Rhône",                       region: "Auvergne-Rhône-Alpes" },
  { code: '70', slug: 'haute-saone',                name: "Haute-Saône",                 region: "Bourgogne-Franche-Comté" },
  { code: '71', slug: 'saone-et-loire',             name: "Saône-et-Loire",              region: "Bourgogne-Franche-Comté" },
  { code: '72', slug: 'sarthe',                     name: "Sarthe",                      region: "Pays de la Loire" },
  { code: '73', slug: 'savoie',                     name: "Savoie",                      region: "Auvergne-Rhône-Alpes" },
  { code: '74', slug: 'haute-savoie',               name: "Haute-Savoie",                region: "Auvergne-Rhône-Alpes" },
  { code: '75', slug: 'paris',                      name: "Paris",                       region: "Île-de-France" },
  { code: '76', slug: 'seine-maritime',             name: "Seine-Maritime",              region: "Normandie" },
  { code: '77', slug: 'seine-et-marne',             name: "Seine-et-Marne",              region: "Île-de-France" },
  { code: '78', slug: 'yvelines',                   name: "Yvelines",                    region: "Île-de-France" },
  { code: '79', slug: 'deux-sevres',                name: "Deux-Sèvres",                 region: "Nouvelle-Aquitaine" },
  { code: '80', slug: 'somme',                      name: "Somme",                       region: "Hauts-de-France" },
  { code: '81', slug: 'tarn',                       name: "Tarn",                        region: "Occitanie" },
  { code: '82', slug: 'tarn-et-garonne',            name: "Tarn-et-Garonne",             region: "Occitanie" },
  { code: '83', slug: 'var',                        name: "Var",                         region: "Provence-Alpes-Côte d'Azur" },
  { code: '84', slug: 'vaucluse',                   name: "Vaucluse",                    region: "Provence-Alpes-Côte d'Azur" },
  { code: '85', slug: 'vendee',                     name: "Vendée",                      region: "Pays de la Loire" },
  { code: '86', slug: 'vienne',                     name: "Vienne",                      region: "Nouvelle-Aquitaine" },
  { code: '87', slug: 'haute-vienne',               name: "Haute-Vienne",                region: "Nouvelle-Aquitaine" },
  { code: '88', slug: 'vosges',                     name: "Vosges",                      region: "Grand Est" },
  { code: '89', slug: 'yonne',                      name: "Yonne",                       region: "Bourgogne-Franche-Comté" },
  { code: '90', slug: 'territoire-de-belfort',      name: "Territoire de Belfort",       region: "Bourgogne-Franche-Comté" },
  { code: '91', slug: 'essonne',                    name: "Essonne",                     region: "Île-de-France" },
  { code: '92', slug: 'hauts-de-seine',             name: "Hauts-de-Seine",              region: "Île-de-France" },
  { code: '93', slug: 'seine-saint-denis',          name: "Seine-Saint-Denis",           region: "Île-de-France" },
  { code: '94', slug: 'val-de-marne',               name: "Val-de-Marne",                region: "Île-de-France" },
  { code: '95', slug: 'val-d-oise',                 name: "Val-d'Oise",                  region: "Île-de-France" },
  { code: '971', slug: 'guadeloupe',                name: "Guadeloupe",                  region: "Guadeloupe" },
  { code: '972', slug: 'martinique',                name: "Martinique",                  region: "Martinique" },
  { code: '973', slug: 'guyane',                    name: "Guyane",                      region: "Guyane" },
  { code: '974', slug: 'la-reunion',                name: "La Réunion",                  region: "La Réunion" },
  { code: '976', slug: 'mayotte',                   name: "Mayotte",                     region: "Mayotte" },
];

export function getDepartmentBySlug(slug: string): DepartmentData | undefined {
  return DEPARTMENTS.find(d => d.slug === slug);
}

export function getDepartmentByCode(code: string): DepartmentData | undefined {
  return DEPARTMENTS.find(d => d.code === code);
}

export function getAllDepartmentSlugs(): string[] {
  return DEPARTMENTS.map(d => d.slug);
}
